### ISSUE TITLE
Reduce nested code

### ISSUE THREAD

**Issue by kl23** [wowselim/matchmaker#1]
https://github.com/wowselim/matchmaker/blob/fed4910594505538927042325127946a2ae2b5a1/src/main/kotlin/co/selim/matchmaker/MainVerticle.kt#L83-L101

if (lobby == null) {  webSocket.error(401, "Unauthorized"); }
if ( lobby.free > 0 ) { webSocket.error(403, "Lobby is full"); }
...

**Comment by wowselim** [comment]
fixed in latest version
